In [8]:
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Initial array:")
print(arr)

col = np.arange(6, 11).reshape(-1, 1)
print("Column to append:")
print(col)


arr_reshaped = arr.reshape(-1, 1)
result = np.append(arr_reshaped, col, axis=1)
print("After appending column-wise:")
print(result)


Initial array:
[1 2 3 4 5]
Column to append:
[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
After appending column-wise:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [9]:
import numpy as np

# 2D array
arr = np.array([[1, 2, 3, 4, 5]])
print("Initial 2D array:")
print(arr)


row = np.array([6, 7, 8, 9, 10]).reshape(1, -1)
print("Row to append:")
print(row)

result = np.append(arr, row, axis=0)
print("After appending row-wise:")
print(result)


Initial 2D array:
[[1 2 3 4 5]]
Row to append:
[[ 6  7  8  9 10]]
After appending row-wise:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:")
print(arr_1d)

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:")
print(arr_2d)

1D array:
[1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]
